config/routes.rb
Rails.application.routes.draw do
  root to: 'articles#index'

  devise_for :users

  devise_scope :user do
    post 'user/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  resources :articles do
    resource :like,      only: [:show, :create, :destroy]
    resources :comments, only: [:create]
  end

  resources :accounts, only: [:show] do
    resources :relationships, only: [:create, :destroy]
  end
  
  resource :timeline, only: [:show]
  resource :profile,  only: [:show, :new, :create, :edit, :update]

  # Stripeのルーティング
  resources :payments
end

app/views/commons/_article.html.haml
.f-container
  %h2.article_title
    = article&.title

  %div.dropdown
    = render 'commons/dropbtn', article: @article
      
.article_content
= simple_format(h(article&.content))

app/views/commons/_articles.html.haml
%main.container
  - if @articles.each do |article|
    %article.article_card
      = link_to article_path(article) do
        .article_data
          %p= "#{article.author_name}が#{article.display_created_at}に投稿"
        %h3.card_title
          = article&.title
  - end.empty?
    %center= '誰かをフォローして記事を表示しよう！'

app/views/commons/_comment.html.haml
%ul.comment_contents
  - @comments.each do |comment|  
    %li.commnet_card.container
      = link_to account_path(comment.user) do
        .f-container
          %p.comments_author= "#{comment.user.name}"
          %p.comment_date= "#{comment.created_at}"
      = simple_format(h(comment.content))
  %hr
.comment_form
  - if user_signed_in?
    = form_with(model: [@user, @article, @comment], local: true) do |f|

      = f.hidden_field :user_name

      = f.text_area :content, class: 'comment_area', presence: true, placeholder: 'この投稿にコメントする'

      = f.submit 'コメントする', class: 'comment_btn'

app/views/commons/_dropbtn.html.haml
- if user_signed_in? && current_user.has_written?(article)
	%button#article__btn.dropdown__btn
		= image_tag asset_path('down-arrow.svg')
	%div.dropdown__body--article
		%ul.dropdown__list
			%li.dropdown__item
				%center= link_to '編集する', edit_article_path(article)
			%li.dropdown__item
				%center= link_to '削除する', article_path(article), data: { method: 'delete', confirm: '本当に削除してもいいですか？'}

app/views/commons/_headline.html.haml
// アーティクルの目次をスクレイピングするレイアウトファイル
%div
  - contents = yield
  %h1 目次
  - node = Nokogiri::HTML.parse contents
  %ul
    - node.css('h2').each do |header|
      %li= header.text
  %h1 内容
  = contents

app/views/commons/_like.html.haml
.f-container

  = link_to account_path(article.user) do
    - if article.user&.avatar&.present?
      = image_tag article.user.avatar.to_s, class: 'circle_icon'
    - else
      = image_tag asset_path('default-avatar.png'), class: 'circle_icon'
  .f-container.vertical
    .article_author
      %p= "#{article.author_name}"
    .article_date
      %p= "#{article.display_created_at}"

  - if user_signed_in?
    .article_heart.hidden.active-heart
      = image_tag 'active-heart.svg'
    .article_heart.hidden.non-active-heart
      = image_tag 'non-active-heart.svg'

app/views/commons/_payment.html.haml
%p= "¥#{article.price}"
= form_tag payments_path, id:"payForm" do
    %script{:src => "https://checkout.stripe.com/checkout.js",
            class: 'stripe-button',
    }
        = hidden_field_tag 'stripeToken'
        = hidden_field_tag 'amount', article.price
        = hidden_field_tag 'stripeEmail'

        = hidden_field_tag 'user_id', current_user.id
        = hidden_field_tag "article_id", article.id

app/views/commons/_profile.html.haml
%main.outer
  %section.profile_sidebar
    .container
      - if user&.avatar&.present?
        %center
          = image_tag user.avatar.to_s, class: 'circle_icon_lg'
      - else
        %center
          = image_tag asset_path('default-avatar.png'), class: 'circle_icon_lg'

      %center= user&.name
      .container
        = simple_format(h(@profile&.bio))
    
    .btn_handler
      - if current_user == user
        = link_to '編集する', edit_profile_path(@profile)
      - else
        = render 'relationships/follow', user: @profile.user
  %section.inner
    = render 'commons/articles'

app/views/commons/_tabs.html.haml
%main.tabs.vertical.block_btn
  %aside.tab
    %i.fas.fa-home.fa-lg
    = link_to 'ホーム', articles_path(current_user)
  %aside.tab
    %i.fas.fa-stream.fa-lg
    = link_to 'タイムライン', timeline_path(current_user)