config/routes.rb
Rails.application.routes.draw do
  root to: 'articles#index'

  devise_for :users

  devise_scope :user do
    post 'user/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  resources :articles do
    resource :like,      only: [:show, :create, :destroy]
    resources :comments, only: [:create]
  end

  resources :accounts, only: [:show] do
    resources :relationships, only: [:create, :destroy]
  end
  
  resource :timeline, only: [:show]
  resource :profile,  only: [:show, :new, :create, :edit, :update]

  # Stripeのルーティング
  resources :payments
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title study-app
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    %script{:crossorigin => "anonymous", :integrity => "sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo", :src => "https://code.jquery.com/jquery-3.3.1.slim.min.js"}
    %script{:crossorigin => "anonymous", :integrity => "sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49", :src => "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"}
    %script{:crossorigin => "anonymous", :integrity => "sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy", :src => "https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"}
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    - if user_signed_in?
      - if user_signed_in?
        .header
          .f-container
            %p.app_name
              = link_to 'AdStudy', root_path
            %div.dropdown.inheader
              %button#dropdown__btn.dropdown__btn
                - if current_user&.avatar&.present?
                  = image_tag current_user.avatar.to_s, class: 'circle_icon'      
                - else
                  = image_tag asset_path('default-avatar.png'), class: 'circle_icon'
              %div.dropdown__body--header
                %ul.dropdown__list
                  %li.dropdown__item
                    %center= link_to 'マイページ', profile_path(current_user)
                  %li.dropdown__item
                    %center= link_to 'ログアウト', destroy_user_session_path, data: { method: 'delete' }
            %div.header_btn
              %i.fas.fa-pen-square.fa-lg
              = link_to '投稿する', new_article_path
            
      - else
        = link_to 'ログイン', new_user_session_path, class: 'header_loginBtn'
        = link_to '新規登録', new_user_registration_path, class: 'header_registrationBtn'
    - else
      - link_to 'root_path'

    - if flash.present?
      .flash
        - flash.each do |key, value|
          %div{:class => key}= value
    = yield